name: Brady Tuazon
favicon: null
layout_spectrum: 0.82283
typography_spectrum: 0.49994
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#dfddde'
    - '#a8b4bf'
    - '#272c28'
    - '#9c8062'
    - '#6b3f29'
  brandStrength: 0.5
  lightness: 0.8125
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
